### PR TITLE
Add recurring events support

### PR DESCRIPTION
**Pull request by rickychilcott**
Address #45

### CODE REVIEW

**Comment by rickychilcott** [comment]
We use the `calendar-recurrence` gem to build up the occurrences, but instead of working with them directly, we duplicate the base event and change the `dtstart` and `dtend` to coincide with that occurrence.

I'm a little concerned about duplicate events, but my tests say it's not an issue. Needs checking...

Wondering if the documentation and the implementation feel right.

**Comment by rickychilcott** [comment]
@whatnotery - I was able to get your commit in (and updated the specs to reflect dropping the original event) in 1fe0464.

Can you try this branch once more and make sure it works for your needs? BTW, do you think the documentation is clear?

**Comment by rickychilcott** [comment]
Actually @whatnotery, now that I think about it dropping the first occurrence might be wrong. 

Imagine a recurring event defined 2 years ago. Asking for the occurrences between today and next year would give you all of those occurrence, none of which should be dropped. 

I’ll need to work out this I tests tomorrow/this weekend.

**Comment by whatnotery** [comment]
This commit resolves the issue as far as I can tell from the testing I did in my dummy applications. It doesn't do the drop(1) so events down the line aren't dropped but it utilizes the first occurrence from .occurrences_between instead from the initial parse

https://github.com/Rakefire/jekyll-ical-tag/commit/2526d40ac5f1e7335ea2208328afdb7d01175d39

**Comment by rickychilcott** [comment]
Hmm I'm not sure about 2526d40ac5f1e7335ea2208328afdb7d01175d39. My read of that code is that it won't even include ANY recurring events. 

Either way, I think ca653dfb6c5a11b644fdf27d76f2ea84067f1ae9 and 6c066e141ca505e3d9568ee4228d963253531fea will do it, and I think my tests prove it properly.

**Comment by rickychilcott** [comment]
OK. Maybe i see how 2526d40ac5f1e7335ea2208328afdb7d01175d39 would do it. Every event (even if it isn't a recurring event) will have "occurrences"

I think that could would negatively interact with other filters though because of how @recurring_start_date and @recurring_end_date would limit. I think I like my solution, but I'm not 100% sure it's right.

Thanks for working through this with me.

**Comment by whatnotery** [comment]
Yeah of course! Thanks for being such an awesome maintainer! It's crazy to me to have made a feature request and to have the feature built by the maintainer less than two days later. Thank you so much. I'll test it out later this evening or tomorrow

**Comment by rickychilcott** [comment]
Available in version 1.6.0. Thanks @whatnotery!

**Pull request merged**
